// auth options
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_DOING = "SIGNIN_DOING";

// admin employee options
export const FETCH_EMPLOYEE_DOING = "FETCH_EMPLOYEE_DOING";
export const FETCH_EMPLOYEE_SUCCESS = "FETCH_EMPLOYEE_SUCCESS";
export const CREATE_EMPLOYEE_DOING = "CREATE_EMPLOYEE_DOING";
export const CREATE_EMPLOYEE_SUCCESS = "CREATE_EMPLOYEE_SUCCESS";
export const DELETE_EMPLOYEE_SUCCESS = "DELETE_EMPLOYEE_SUCCESS";
export const UPDATE_EMPLOYEE_SUCCESS = "UPDATE_EMPLOYEE_SUCCESS";
