// auth options
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_DOING = "SIGNIN_DOING";

// admin employee options
export const FETCH_EMPLOYEES_DOING = "FETCH_EMPLOYEES_DOING";
export const FETCH_EMPLOYEES_SUCCESS = "FETCH_EMPLOYEES_SUCCESS";
export const CREATE_EMPLOYEE_DOING = "CREATE_EMPLOYEE_DOING";
export const CREATE_EMPLOYEE_SUCCESS = "CREATE_EMPLOYEE_SUCCESS";
export const DELETE_EMPLOYEE_DOING = "DELETE_EMPLOYEE_DOING";
export const DELETE_EMPLOYEE_SUCCESS = "DELETE_EMPLOYEE_SUCCESS";
export const UPDATE_EMPLOYEE_DOING = "UPDATE_EMPLOYEE_DOING";
export const UPDATE_EMPLOYEE_SUCCESS = "UPDATE_EMPLOYEE_SUCCESS";

// admin review options
export const CREATE_REVIEW_DOING = "CREATE_REVIEW_DOING";
export const CREATE_REVIEW_SUCCESS = "CREATE_REVIEW_SUCCESS";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const FETCH_RECEIVED_REVIEWS_DOING = "FETCH_RECEIVED_REVIEWS_DOING";
export const FETCH_RECEIVED_REVIEWS_SUCCESS = "FETCH_RECEIVED_REVIEWS_SUCCESS";

// employee review options
export const FETCH_ASSIGNMENT_REVIEWS_SUCCESS = "FETCH_ASSIGNMENT_REVIEWS_SUCCESS";
export const SUBMIT_REVIEW_SUCCESS = "SUBMIT_REVIEW_SUCCESS";